# Site settings
title: [ARCHIVED] scanf - blog, see http://blog.alemayhu.com
email: alexander@alemayhu.com
description: > # this means to ignore newlines until "baseurl:"
  A place for random thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scanf.github.io" # the base hostname & protocol for your site
twitter_username: aalemayhu
github_username:  scanf

# Build settings
markdown: kramdown
gems:
  - jemoji
